# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/fifo_line/fifo_line.xci
# IP: The module: 'fifo_line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/fifo_line/fifo_line.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_line'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/fifo_line/fifo_line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_line'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/fifo_line/fifo_line.xci
# IP: The module: 'fifo_line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/fifo_line/fifo_line.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_line'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/fifo_line/fifo_line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_line'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
