// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AXIvideo2Mat (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        video_in_TDATA,
        video_in_TVALID,
        video_in_TREADY,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        img_rows_V_dout,
        img_rows_V_empty_n,
        img_rows_V_read,
        img_cols_V_dout,
        img_cols_V_empty_n,
        img_cols_V_read,
        img_data_stream_V_din,
        img_data_stream_V_full_n,
        img_data_stream_V_write,
        img_rows_V_out_din,
        img_rows_V_out_full_n,
        img_rows_V_out_write,
        img_cols_V_out_din,
        img_cols_V_out_full_n,
        img_cols_V_out_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_pp1_stage0 = 8'd16;
parameter    ap_ST_fsm_state7 = 8'd32;
parameter    ap_ST_fsm_state8 = 8'd64;
parameter    ap_ST_fsm_state9 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] video_in_TDATA;
input   video_in_TVALID;
output   video_in_TREADY;
input  [7:0] video_in_TKEEP;
input  [7:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
input  [9:0] img_rows_V_dout;
input   img_rows_V_empty_n;
output   img_rows_V_read;
input  [10:0] img_cols_V_dout;
input   img_cols_V_empty_n;
output   img_cols_V_read;
output  [7:0] img_data_stream_V_din;
input   img_data_stream_V_full_n;
output   img_data_stream_V_write;
output  [9:0] img_rows_V_out_din;
input   img_rows_V_out_full_n;
output   img_rows_V_out_write;
output  [10:0] img_cols_V_out_din;
input   img_cols_V_out_full_n;
output   img_cols_V_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg video_in_TREADY;
reg img_rows_V_read;
reg img_cols_V_read;
reg img_data_stream_V_write;
reg img_rows_V_out_write;
reg img_cols_V_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    video_in_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire   [0:0] exitcond_i_fu_376_p2;
wire   [0:0] brmerge_i_fu_390_p2;
wire    ap_CS_fsm_state8;
wire   [0:0] ap_phi_mux_eol_2_i_phi_fu_331_p4;
reg    img_rows_V_blk_n;
reg    img_cols_V_blk_n;
reg    img_data_stream_V_blk_n;
reg    ap_enable_reg_pp1_iter1;
reg   [0:0] exitcond_i_reg_444;
reg    img_rows_V_out_blk_n;
reg    img_cols_V_out_blk_n;
reg   [0:0] eol_reg_234;
reg   [63:0] axi_data_V_1_i_reg_245;
reg   [31:0] t_V_2_reg_256;
reg   [0:0] eol_i_reg_267;
reg   [0:0] axi_last_V_2_i_reg_279;
reg   [63:0] p_Val2_s_reg_292;
wire  signed [31:0] rows_V_fu_348_p1;
reg  signed [31:0] rows_V_reg_405;
reg    ap_block_state1;
wire  signed [31:0] cols_V_fu_352_p1;
reg  signed [31:0] cols_V_reg_410;
reg   [63:0] tmp_data_V_reg_415;
reg   [0:0] tmp_last_V_reg_423;
wire   [0:0] exitcond2_i_fu_365_p2;
wire    ap_CS_fsm_state4;
wire   [31:0] i_V_fu_370_p2;
reg   [31:0] i_V_reg_439;
reg    ap_predicate_op65_read_state5;
reg    ap_block_state5_pp1_stage0_iter0;
reg    ap_block_state6_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [31:0] j_V_fu_381_p2;
wire   [7:0] tmp_fu_396_p1;
reg   [7:0] tmp_reg_457;
reg    ap_block_state8;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state5;
reg   [0:0] axi_last_V_3_i_reg_304;
reg   [0:0] axi_last_V1_i_reg_203;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state3;
reg   [63:0] axi_data_V_3_i_reg_316;
reg   [63:0] axi_data_V1_i_reg_213;
reg   [31:0] t_V_reg_223;
reg   [0:0] ap_phi_mux_eol_phi_fu_237_p4;
reg   [63:0] ap_phi_mux_axi_data_V_1_i_phi_fu_248_p4;
reg   [0:0] ap_phi_mux_eol_i_phi_fu_271_p4;
wire   [0:0] ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_279;
reg   [63:0] ap_phi_mux_p_Val2_s_phi_fu_296_p4;
wire   [63:0] ap_phi_reg_pp1_iter0_p_Val2_s_reg_292;
wire    ap_CS_fsm_state7;
reg   [0:0] eol_2_i_reg_328;
reg    ap_block_pp1_stage0_01001;
reg   [0:0] sof_1_i_fu_146;
wire  signed [9:0] rows_V_fu_348_p0;
wire  signed [10:0] cols_V_fu_352_p0;
wire   [0:0] tmp_user_V_fu_356_p1;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_261;
reg    ap_condition_184;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (exitcond2_i_fu_365_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state5) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((exitcond2_i_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state5) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((exitcond2_i_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        axi_data_V1_i_reg_213 <= tmp_data_V_reg_415;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        axi_data_V1_i_reg_213 <= axi_data_V_3_i_reg_316;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        axi_data_V_1_i_reg_245 <= p_Val2_s_reg_292;
    end else if (((exitcond2_i_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        axi_data_V_1_i_reg_245 <= axi_data_V1_i_reg_213;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        axi_data_V_3_i_reg_316 <= axi_data_V_1_i_reg_245;
    end else if ((~((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0)) & (eol_2_i_reg_328 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        axi_data_V_3_i_reg_316 <= video_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        axi_last_V1_i_reg_203 <= tmp_last_V_reg_423;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        axi_last_V1_i_reg_203 <= axi_last_V_3_i_reg_304;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if (((brmerge_i_fu_390_p2 == 1'd1) & (exitcond_i_fu_376_p2 == 1'd0))) begin
            axi_last_V_2_i_reg_279 <= ap_phi_mux_eol_phi_fu_237_p4;
        end else if (((brmerge_i_fu_390_p2 == 1'd0) & (exitcond_i_fu_376_p2 == 1'd0))) begin
            axi_last_V_2_i_reg_279 <= video_in_TLAST;
        end else if ((1'b1 == 1'b1)) begin
            axi_last_V_2_i_reg_279 <= ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_279;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        axi_last_V_3_i_reg_304 <= eol_reg_234;
    end else if ((~((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0)) & (eol_2_i_reg_328 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        axi_last_V_3_i_reg_304 <= video_in_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        eol_2_i_reg_328 <= eol_i_reg_267;
    end else if ((~((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0)) & (eol_2_i_reg_328 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        eol_2_i_reg_328 <= video_in_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        eol_i_reg_267 <= axi_last_V_2_i_reg_279;
    end else if (((exitcond2_i_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        eol_i_reg_267 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        eol_reg_234 <= axi_last_V_2_i_reg_279;
    end else if (((exitcond2_i_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        eol_reg_234 <= axi_last_V1_i_reg_203;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if (((brmerge_i_fu_390_p2 == 1'd1) & (exitcond_i_fu_376_p2 == 1'd0))) begin
            p_Val2_s_reg_292 <= ap_phi_mux_axi_data_V_1_i_phi_fu_248_p4;
        end else if (((brmerge_i_fu_390_p2 == 1'd0) & (exitcond_i_fu_376_p2 == 1'd0))) begin
            p_Val2_s_reg_292 <= video_in_TDATA;
        end else if ((1'b1 == 1'b1)) begin
            p_Val2_s_reg_292 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_292;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_376_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sof_1_i_fu_146 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        sof_1_i_fu_146 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_376_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        t_V_2_reg_256 <= j_V_fu_381_p2;
    end else if (((exitcond2_i_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        t_V_2_reg_256 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        t_V_reg_223 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        t_V_reg_223 <= i_V_reg_439;
    end
end

always @ (posedge ap_clk) begin
    if ((~((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_V_reg_410 <= cols_V_fu_352_p1;
        rows_V_reg_405 <= rows_V_fu_348_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_i_reg_444 <= exitcond_i_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_V_reg_439 <= i_V_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((video_in_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_data_V_reg_415 <= video_in_TDATA;
        tmp_last_V_reg_423 <= video_in_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_376_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_reg_457 <= tmp_fu_396_p1;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_376_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond2_i_fu_365_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_axi_data_V_1_i_phi_fu_248_p4 = p_Val2_s_reg_292;
    end else begin
        ap_phi_mux_axi_data_V_1_i_phi_fu_248_p4 = axi_data_V_1_i_reg_245;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_eol_i_phi_fu_271_p4 = axi_last_V_2_i_reg_279;
    end else begin
        ap_phi_mux_eol_i_phi_fu_271_p4 = eol_i_reg_267;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_eol_phi_fu_237_p4 = axi_last_V_2_i_reg_279;
    end else begin
        ap_phi_mux_eol_phi_fu_237_p4 = eol_reg_234;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_261)) begin
        if ((brmerge_i_fu_390_p2 == 1'd1)) begin
            ap_phi_mux_p_Val2_s_phi_fu_296_p4 = ap_phi_mux_axi_data_V_1_i_phi_fu_248_p4;
        end else if ((brmerge_i_fu_390_p2 == 1'd0)) begin
            ap_phi_mux_p_Val2_s_phi_fu_296_p4 = video_in_TDATA;
        end else begin
            ap_phi_mux_p_Val2_s_phi_fu_296_p4 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_292;
        end
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_296_p4 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_292;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_blk_n = img_cols_V_empty_n;
    end else begin
        img_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_out_blk_n = img_cols_V_out_full_n;
    end else begin
        img_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_out_write = 1'b1;
    end else begin
        img_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_read = 1'b1;
    end else begin
        img_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        img_data_stream_V_blk_n = img_data_stream_V_full_n;
    end else begin
        img_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_444 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        img_data_stream_V_write = 1'b1;
    end else begin
        img_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_blk_n = img_rows_V_empty_n;
    end else begin
        img_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_out_blk_n = img_rows_V_out_full_n;
    end else begin
        img_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_out_write = 1'b1;
    end else begin
        img_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_read = 1'b1;
    end else begin
        img_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond2_i_fu_365_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((brmerge_i_fu_390_p2 == 1'd0) & (exitcond_i_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((eol_2_i_reg_328 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        video_in_TDATA_blk_n = video_in_TVALID;
    end else begin
        video_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_predicate_op65_read_state5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((video_in_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | (~((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0)) & (eol_2_i_reg_328 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        video_in_TREADY = 1'b1;
    end else begin
        video_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_user_V_fu_356_p1 == 1'd0) & (video_in_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((video_in_TVALID == 1'b1) & (tmp_user_V_fu_356_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond2_i_fu_365_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((exitcond_i_fu_376_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((exitcond_i_fu_376_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if ((~((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0)) & (eol_2_i_reg_328 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state8) & (ap_phi_mux_eol_2_i_phi_fu_331_p4 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((video_in_TVALID == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_predicate_op65_read_state5 == 1'b1)) | ((exitcond_i_reg_444 == 1'd0) & (img_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((video_in_TVALID == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_predicate_op65_read_state5 == 1'b1)) | ((exitcond_i_reg_444 == 1'd0) & (img_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((video_in_TVALID == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_predicate_op65_read_state5 == 1'b1)) | ((exitcond_i_reg_444 == 1'd0) & (img_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp1_stage0_iter0 = ((video_in_TVALID == 1'b0) & (ap_predicate_op65_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp1_stage0_iter1 = ((exitcond_i_reg_444 == 1'd0) & (img_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state8 = ((eol_2_i_reg_328 == 1'd0) & (video_in_TVALID == 1'b0));
end

always @ (*) begin
    ap_condition_184 = ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001));
end

always @ (*) begin
    ap_condition_261 = ((exitcond_i_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_eol_2_i_phi_fu_331_p4 = eol_2_i_reg_328;

assign ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_279 = 'bx;

assign ap_phi_reg_pp1_iter0_p_Val2_s_reg_292 = 'bx;

always @ (*) begin
    ap_predicate_op65_read_state5 = ((brmerge_i_fu_390_p2 == 1'd0) & (exitcond_i_fu_376_p2 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign brmerge_i_fu_390_p2 = (sof_1_i_fu_146 | ap_phi_mux_eol_i_phi_fu_271_p4);

assign cols_V_fu_352_p0 = img_cols_V_dout;

assign cols_V_fu_352_p1 = cols_V_fu_352_p0;

assign exitcond2_i_fu_365_p2 = ((t_V_reg_223 == rows_V_reg_405) ? 1'b1 : 1'b0);

assign exitcond_i_fu_376_p2 = ((t_V_2_reg_256 == cols_V_reg_410) ? 1'b1 : 1'b0);

assign i_V_fu_370_p2 = (t_V_reg_223 + 32'd1);

assign img_cols_V_out_din = img_cols_V_dout;

assign img_data_stream_V_din = tmp_reg_457;

assign img_rows_V_out_din = img_rows_V_dout;

assign j_V_fu_381_p2 = (t_V_2_reg_256 + 32'd1);

assign rows_V_fu_348_p0 = img_rows_V_dout;

assign rows_V_fu_348_p1 = rows_V_fu_348_p0;

assign start_out = real_start;

assign tmp_fu_396_p1 = ap_phi_mux_p_Val2_s_phi_fu_296_p4[7:0];

assign tmp_user_V_fu_356_p1 = video_in_TUSER;

endmodule //AXIvideo2Mat
