# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/design_1_canny_bd_0_0.xci
# IP: The module: 'design_1_canny_bd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_maxtri3x3_shift_0_0/canny_bd_maxtri3x3_shift_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_maxtri3x3_shift_0_0 || ORIG_REF_NAME==canny_bd_maxtri3x3_shift_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_sobel3x3_algorithm_0_0/canny_bd_sobel3x3_algorithm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_sobel3x3_algorithm_0_0 || ORIG_REF_NAME==canny_bd_sobel3x3_algorithm_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_maxtri3x3_SobelDir_0_0/canny_bd_maxtri3x3_SobelDir_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_maxtri3x3_SobelDir_0_0 || ORIG_REF_NAME==canny_bd_maxtri3x3_SobelDir_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_SobelDir/fifo_SobelDir.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_SobelDir || ORIG_REF_NAME==fifo_SobelDir} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_canny_NonMaxSupp_0_0/canny_bd_canny_NonMaxSupp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_canny_NonMaxSupp_0_0 || ORIG_REF_NAME==canny_bd_canny_NonMaxSupp_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_maxtri3x3_CannyNMS_0_0/canny_bd_maxtri3x3_CannyNMS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_maxtri3x3_CannyNMS_0_0 || ORIG_REF_NAME==canny_bd_maxtri3x3_CannyNMS_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_CannyNMS || ORIG_REF_NAME==fifo_CannyNMS} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_canny_HystThreshold_0_0/canny_bd_canny_HystThreshold_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_canny_HystThreshold_0_0 || ORIG_REF_NAME==canny_bd_canny_HystThreshold_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_img_edge_cut_0_0/canny_bd_img_edge_cut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_img_edge_cut_0_0 || ORIG_REF_NAME==canny_bd_img_edge_cut_0_0} -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_SobelDir/fifo_SobelDir.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_SobelDir || ORIG_REF_NAME==fifo_SobelDir} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_CannyNMS || ORIG_REF_NAME==fifo_CannyNMS} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_canny_bd_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/design_1_canny_bd_0_0.xci
# IP: The module: 'design_1_canny_bd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_maxtri3x3_shift_0_0/canny_bd_maxtri3x3_shift_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_maxtri3x3_shift_0_0 || ORIG_REF_NAME==canny_bd_maxtri3x3_shift_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_sobel3x3_algorithm_0_0/canny_bd_sobel3x3_algorithm_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_sobel3x3_algorithm_0_0 || ORIG_REF_NAME==canny_bd_sobel3x3_algorithm_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_maxtri3x3_SobelDir_0_0/canny_bd_maxtri3x3_SobelDir_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_maxtri3x3_SobelDir_0_0 || ORIG_REF_NAME==canny_bd_maxtri3x3_SobelDir_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_SobelDir/fifo_SobelDir.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_SobelDir || ORIG_REF_NAME==fifo_SobelDir} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_canny_NonMaxSupp_0_0/canny_bd_canny_NonMaxSupp_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_canny_NonMaxSupp_0_0 || ORIG_REF_NAME==canny_bd_canny_NonMaxSupp_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_maxtri3x3_CannyNMS_0_0/canny_bd_maxtri3x3_CannyNMS_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_maxtri3x3_CannyNMS_0_0 || ORIG_REF_NAME==canny_bd_maxtri3x3_CannyNMS_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_CannyNMS || ORIG_REF_NAME==fifo_CannyNMS} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_canny_HystThreshold_0_0/canny_bd_canny_HystThreshold_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_canny_HystThreshold_0_0 || ORIG_REF_NAME==canny_bd_canny_HystThreshold_0_0} -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_img_edge_cut_0_0/canny_bd_img_edge_cut_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canny_bd_img_edge_cut_0_0 || ORIG_REF_NAME==canny_bd_img_edge_cut_0_0} -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_SobelDir/fifo_SobelDir.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_SobelDir || ORIG_REF_NAME==fifo_SobelDir} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_CannyNMS || ORIG_REF_NAME==fifo_CannyNMS} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_accelerate/prj_accelerate/prj_accelerate.srcs/sources_1/bd/design_1/ip/design_1_canny_bd_0_0/src/canny_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_canny_bd_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
