# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/cmos10bit_2_8bit_BROM/cmos10bit_2_8bit_BROM.xci
# IP: The module: 'cmos10bit_2_8bit_BROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/cmos10bit_2_8bit_BROM/cmos10bit_2_8bit_BROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmos10bit_2_8bit_BROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/cmos10bit_2_8bit_BROM/cmos10bit_2_8bit_BROM.xci
# IP: The module: 'cmos10bit_2_8bit_BROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/prj_ocr/prj_ocr/prj_ocr.srcs/sources_1/ip/cmos10bit_2_8bit_BROM/cmos10bit_2_8bit_BROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmos10bit_2_8bit_BROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
