// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_otsu (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcImg_rows_V_dout,
        srcImg_rows_V_empty_n,
        srcImg_rows_V_read,
        srcImg_cols_V_dout,
        srcImg_cols_V_empty_n,
        srcImg_cols_V_read,
        srcImg_data_stream_V_dout,
        srcImg_data_stream_V_empty_n,
        srcImg_data_stream_V_read,
        dstImg_data_stream_V_din,
        dstImg_data_stream_V_full_n,
        dstImg_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 56'd1;
parameter    ap_ST_fsm_state2 = 56'd2;
parameter    ap_ST_fsm_state3 = 56'd4;
parameter    ap_ST_fsm_pp0_stage0 = 56'd8;
parameter    ap_ST_fsm_state8 = 56'd16;
parameter    ap_ST_fsm_state9 = 56'd32;
parameter    ap_ST_fsm_state10 = 56'd64;
parameter    ap_ST_fsm_state11 = 56'd128;
parameter    ap_ST_fsm_state12 = 56'd256;
parameter    ap_ST_fsm_state13 = 56'd512;
parameter    ap_ST_fsm_state14 = 56'd1024;
parameter    ap_ST_fsm_state15 = 56'd2048;
parameter    ap_ST_fsm_state16 = 56'd4096;
parameter    ap_ST_fsm_state17 = 56'd8192;
parameter    ap_ST_fsm_state18 = 56'd16384;
parameter    ap_ST_fsm_state19 = 56'd32768;
parameter    ap_ST_fsm_state20 = 56'd65536;
parameter    ap_ST_fsm_state21 = 56'd131072;
parameter    ap_ST_fsm_state22 = 56'd262144;
parameter    ap_ST_fsm_state23 = 56'd524288;
parameter    ap_ST_fsm_state24 = 56'd1048576;
parameter    ap_ST_fsm_state25 = 56'd2097152;
parameter    ap_ST_fsm_state26 = 56'd4194304;
parameter    ap_ST_fsm_state27 = 56'd8388608;
parameter    ap_ST_fsm_state28 = 56'd16777216;
parameter    ap_ST_fsm_state29 = 56'd33554432;
parameter    ap_ST_fsm_state30 = 56'd67108864;
parameter    ap_ST_fsm_state31 = 56'd134217728;
parameter    ap_ST_fsm_state32 = 56'd268435456;
parameter    ap_ST_fsm_state33 = 56'd536870912;
parameter    ap_ST_fsm_state34 = 56'd1073741824;
parameter    ap_ST_fsm_state35 = 56'd2147483648;
parameter    ap_ST_fsm_state36 = 56'd4294967296;
parameter    ap_ST_fsm_state37 = 56'd8589934592;
parameter    ap_ST_fsm_state38 = 56'd17179869184;
parameter    ap_ST_fsm_state39 = 56'd34359738368;
parameter    ap_ST_fsm_state40 = 56'd68719476736;
parameter    ap_ST_fsm_state41 = 56'd137438953472;
parameter    ap_ST_fsm_state42 = 56'd274877906944;
parameter    ap_ST_fsm_state43 = 56'd549755813888;
parameter    ap_ST_fsm_state44 = 56'd1099511627776;
parameter    ap_ST_fsm_state45 = 56'd2199023255552;
parameter    ap_ST_fsm_state46 = 56'd4398046511104;
parameter    ap_ST_fsm_state47 = 56'd8796093022208;
parameter    ap_ST_fsm_state48 = 56'd17592186044416;
parameter    ap_ST_fsm_state49 = 56'd35184372088832;
parameter    ap_ST_fsm_state50 = 56'd70368744177664;
parameter    ap_ST_fsm_state51 = 56'd140737488355328;
parameter    ap_ST_fsm_state52 = 56'd281474976710656;
parameter    ap_ST_fsm_state53 = 56'd562949953421312;
parameter    ap_ST_fsm_state54 = 56'd1125899906842624;
parameter    ap_ST_fsm_state55 = 56'd2251799813685248;
parameter    ap_ST_fsm_state56 = 56'd4503599627370496;
parameter    ap_ST_fsm_state57 = 56'd9007199254740992;
parameter    ap_ST_fsm_state58 = 56'd18014398509481984;
parameter    ap_ST_fsm_state59 = 56'd36028797018963968;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [9:0] srcImg_rows_V_dout;
input   srcImg_rows_V_empty_n;
output   srcImg_rows_V_read;
input  [10:0] srcImg_cols_V_dout;
input   srcImg_cols_V_empty_n;
output   srcImg_cols_V_read;
input  [7:0] srcImg_data_stream_V_dout;
input   srcImg_data_stream_V_empty_n;
output   srcImg_data_stream_V_read;
output  [7:0] dstImg_data_stream_V_din;
input   dstImg_data_stream_V_full_n;
output   dstImg_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcImg_rows_V_read;
reg srcImg_cols_V_read;
reg srcImg_data_stream_V_read;
reg[7:0] dstImg_data_stream_V_din;
reg dstImg_data_stream_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [55:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] threshold_V;
reg    srcImg_rows_V_blk_n;
reg    srcImg_cols_V_blk_n;
reg    srcImg_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_6_i_reg_1350;
reg    dstImg_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_6_i_reg_1350_pp0_iter1_reg;
reg   [0:0] tmp_7_i_reg_1369;
reg   [9:0] j_i_reg_410;
reg  signed [9:0] srcImg_rows_V_read_reg_1243;
reg    ap_block_state1;
reg  signed [10:0] srcImg_cols_V_read_reg_1249;
wire   [8:0] i_fu_474_p2;
wire    ap_CS_fsm_state2;
wire  signed [19:0] extLd12_cast_i_fu_485_p1;
reg  signed [19:0] extLd12_cast_i_reg_1331;
wire   [0:0] exitcond3_i_fu_468_p2;
wire  signed [19:0] extLd_cast_i_fu_488_p1;
reg  signed [19:0] extLd_cast_i_reg_1336;
wire   [0:0] tmp_5_i_fu_535_p2;
wire    ap_CS_fsm_state3;
wire   [8:0] i_1_fu_540_p2;
reg   [8:0] i_1_reg_1345;
wire   [0:0] tmp_6_i_fu_550_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_predicate_op130_write_state6;
reg    ap_predicate_op133_write_state6;
reg    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_6_i_reg_1350_pp0_iter2_reg;
wire   [9:0] j_fu_555_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_3_reg_1359;
wire   [0:0] tmp_7_i_fu_565_p2;
reg   [7:0] addr_win_val_0_V_2_2_reg_1373;
wire   [0:0] tmp_51_i_fu_680_p2;
reg   [0:0] tmp_51_i_reg_1378;
wire   [0:0] tmp_49_1_i_fu_694_p2;
reg   [0:0] tmp_49_1_i_reg_1384;
wire   [0:0] tmp_51_2_i_fu_708_p2;
reg   [0:0] tmp_51_2_i_reg_1390;
wire   [0:0] tmp_34_i_fu_722_p2;
reg   [0:0] tmp_34_i_reg_1396;
wire   [0:0] icmp_fu_748_p2;
reg   [0:0] icmp_reg_1406;
wire   [0:0] sel_tmp5_fu_768_p2;
reg   [0:0] sel_tmp5_reg_1411;
wire   [1:0] m_fu_952_p2;
wire    ap_CS_fsm_state9;
wire  signed [19:0] total_pixs_V_fu_1229_p2;
reg  signed [19:0] total_pixs_V_reg_1438;
wire    ap_CS_fsm_state10;
wire   [8:0] i_2_fu_992_p2;
reg   [8:0] i_2_reg_1458;
wire    ap_CS_fsm_state11;
wire   [63:0] tmp_2_i_fu_998_p1;
reg   [63:0] tmp_2_i_reg_1463;
wire   [0:0] exitcond5_i_fu_986_p2;
wire   [18:0] hist_out_V_q0;
reg   [18:0] hist_out_V_load_reg_1486;
wire    ap_CS_fsm_state12;
wire   [0:0] tmp_15_i_fu_1008_p2;
reg   [0:0] tmp_15_i_reg_1491;
wire   [27:0] front_grays_V_q0;
reg   [27:0] front_grays_V_load_reg_1495;
wire    ap_CS_fsm_state14;
wire   [25:0] tmp_1_i_fu_1058_p1;
reg   [25:0] tmp_1_i_reg_1500;
wire   [8:0] i_3_fu_1067_p2;
reg   [8:0] i_3_reg_1508;
wire    ap_CS_fsm_state15;
reg   [7:0] front_pixs_V_addr_2_reg_1513;
wire   [0:0] exitcond_i_fu_1061_p2;
reg   [27:0] p_Val2_3_reg_1523;
wire    ap_CS_fsm_state16;
wire   [27:0] black_grays_V_fu_1084_p2;
reg   [27:0] black_grays_V_reg_1528;
wire   [19:0] f_op_V_1_fu_1100_p3;
reg   [19:0] f_op_V_1_reg_1536;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire   [25:0] grp_fu_1132_p2;
reg   [25:0] r_V_5_reg_1566;
wire    ap_CS_fsm_state47;
wire   [33:0] grp_fu_1118_p2;
reg   [33:0] r_V_6_reg_1572;
wire    ap_CS_fsm_state54;
wire   [25:0] w1_V_fu_1154_p2;
reg   [25:0] w1_V_reg_1577;
wire    ap_CS_fsm_state55;
wire   [34:0] r_V_fu_1166_p2;
reg   [34:0] r_V_reg_1582;
wire  signed [51:0] tmp9_fu_1181_p2;
reg  signed [51:0] tmp9_reg_1587;
wire    ap_CS_fsm_state56;
wire  signed [51:0] tmp5_fu_1187_p2;
reg  signed [51:0] tmp5_reg_1592;
reg   [33:0] delta_temp_V_reg_1597;
wire    ap_CS_fsm_state58;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter2_state6;
reg    ap_enable_reg_pp0_iter3;
reg   [7:0] front_pixs_V_address0;
reg    front_pixs_V_ce0;
reg    front_pixs_V_we0;
reg   [19:0] front_pixs_V_d0;
wire   [19:0] front_pixs_V_q0;
reg   [7:0] front_grays_V_address0;
reg    front_grays_V_ce0;
reg    front_grays_V_we0;
reg   [27:0] front_grays_V_d0;
reg   [7:0] hist_out_V_address0;
reg    hist_out_V_ce0;
reg    hist_out_V_we0;
reg   [7:0] hist_out_V_address1;
reg    hist_out_V_ce1;
reg    hist_out_V_we1;
reg   [18:0] hist_out_V_d1;
reg   [8:0] i3_i_reg_388;
reg   [8:0] i4_i_reg_399;
wire    ap_CS_fsm_state8;
reg   [1:0] col_assign_reg_421;
wire   [0:0] exitcond4_i_fu_946_p2;
reg   [8:0] i_op_assign_reg_432;
wire    ap_CS_fsm_state13;
reg   [8:0] val_assign_reg_444;
wire    ap_CS_fsm_state59;
wire   [63:0] tmp_3_i_fu_480_p1;
wire   [63:0] tmp_35_i_fu_728_p1;
wire   [63:0] tmp_39_i_fu_917_p1;
wire   [63:0] tmp_i_19_fu_972_p1;
wire   [63:0] tmp_20_i_fu_1073_p1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_2_fu_1215_p1;
wire   [0:0] tmp_32_i_fu_1210_p2;
reg   [18:0] hist_win_val_0_V_1_fu_206;
wire   [18:0] hist_win_val_0_V_1_3_fu_883_p3;
reg   [7:0] addr_win_val_0_V_1_fu_210;
wire   [7:0] addr_win_val_0_V_1_1_fu_714_p3;
reg   [7:0] addr_win_val_0_V_2_fu_214;
reg   [7:0] addr_win_val_0_V_1_2_fu_218;
wire   [7:0] addr_win_val_V_0_0_2_fu_781_p3;
reg   [7:0] addr_win_val_0_V_3_fu_222;
reg   [7:0] addr_last_V_fu_226;
reg   [18:0] hist_win_val_0_V_2_fu_230;
wire   [18:0] hist_win_val_0_V_1_2_fu_876_p3;
reg   [18:0] hist_win_val_0_V_1_4_fu_234;
wire   [18:0] hist_win_val_V_0_0_2_fu_910_p3;
reg   [18:0] hist_win_val_0_V_3_fu_238;
wire   [18:0] hist_win_val_0_V_2_2_fu_855_p3;
reg   [18:0] hist_win_val_0_V_3_4_fu_242;
wire   [18:0] hist_win_val_0_V_3_2_fu_835_p3;
reg   [27:0] front_grays_tmp_V_1_fu_246;
wire   [27:0] grp_fu_1233_p3;
reg   [19:0] front_pixs_tmp_V_1_fu_250;
wire   [19:0] front_pixs_tmp_V_fu_1022_p2;
reg   [33:0] delta_max_V_fu_254;
wire   [18:0] hist_win_val_V_load_s_fu_977_p3;
wire   [19:0] tmp_16_i_fu_1014_p1;
wire   [0:0] tmp_21_i_fu_1089_p2;
wire   [9:0] i4_cast_cast_i_fu_531_p1;
wire   [10:0] j_cast_cast_i_fu_546_p1;
wire   [0:0] tmp_28_i_fu_580_p2;
wire   [0:0] tmp_28_3_i_fu_595_p2;
wire   [0:0] tmp_7_fu_608_p2;
wire   [2:0] p_i_cast_fu_600_p3;
wire   [0:0] tmp_28_1_i_fu_585_p2;
wire   [0:0] sel_tmp1_fu_622_p2;
wire   [0:0] sel_tmp6_demorgan_fu_634_p2;
wire   [0:0] tmp_28_2_i_fu_590_p2;
wire   [0:0] sel_tmp6_fu_640_p2;
wire   [0:0] sel_tmp7_fu_646_p2;
wire   [0:0] sel_tmp2_fu_628_p2;
wire   [0:0] tmp_8_fu_660_p2;
wire   [2:0] sel_tmp3_cast_fu_652_p3;
wire   [2:0] sel_tmp_fu_614_p3;
wire   [2:0] p_6_i_fu_666_p3;
wire   [2:0] r_V_1_fu_674_p2;
wire   [7:0] addr_win_val_0_V_3_1_fu_686_p3;
wire   [7:0] addr_win_val_0_V_2_1_fu_700_p3;
wire   [1:0] tmp_fu_738_p4;
wire   [0:0] tmp_37_i_fu_732_p2;
wire   [0:0] sel_tmp4_fu_762_p2;
wire   [7:0] storemerge1_i_fu_754_p3;
wire   [7:0] sel_tmp8_fu_774_p3;
wire   [18:0] hist_win_val_0_V_3_1_fu_829_p2;
wire   [18:0] hist_win_val_0_V_2_1_fu_849_p2;
wire   [18:0] hist_win_val_0_V_3_3_fu_842_p3;
wire   [18:0] hist_win_val_0_V_1_1_fu_870_p2;
wire   [18:0] hist_win_val_0_V_2_3_fu_863_p3;
wire   [18:0] hist_win_val_0_V_0_fu_890_p2;
wire   [18:0] storemerge_i_fu_896_p3;
wire   [18:0] hist_last_V_fu_823_p2;
wire   [18:0] sel_tmp9_fu_903_p3;
wire   [0:0] cond_i_fu_958_p2;
wire   [7:0] addr_win_val_V_load_s_fu_964_p3;
wire   [0:0] tmp_22_i_fu_1095_p2;
(* use_dsp48 = "no" *) wire   [19:0] black_pixs_V_fu_1079_p2;
wire   [33:0] grp_fu_1118_p0;
wire   [19:0] grp_fu_1118_p1;
wire   [25:0] grp_fu_1132_p0;
wire   [19:0] grp_fu_1132_p1;
wire   [33:0] grp_fu_1148_p0;
wire   [19:0] grp_fu_1148_p1;
wire   [33:0] grp_fu_1148_p2;
wire   [34:0] tmp_29_i_fu_1159_p1;
wire   [34:0] tmp_30_i_fu_1163_p1;
wire  signed [34:0] tmp9_fu_1181_p0;
wire  signed [51:0] tmp_6_fu_1178_p1;
wire  signed [34:0] tmp9_fu_1181_p1;
wire   [25:0] tmp5_fu_1187_p0;
wire   [25:0] tmp5_fu_1187_p1;
wire    ap_CS_fsm_state57;
wire   [51:0] grp_fu_1193_p2;
wire  signed [10:0] total_pixs_V_fu_1229_p0;
wire  signed [9:0] total_pixs_V_fu_1229_p1;
wire   [18:0] grp_fu_1233_p0;
wire   [8:0] grp_fu_1233_p1;
reg    grp_fu_1118_ap_start;
wire    grp_fu_1118_ap_done;
reg    grp_fu_1132_ap_start;
wire    grp_fu_1132_ap_done;
reg    grp_fu_1148_ap_start;
wire    grp_fu_1148_ap_done;
reg   [55:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [33:0] grp_fu_1118_p10;
wire   [33:0] grp_fu_1148_p10;
wire   [27:0] grp_fu_1233_p00;
wire   [27:0] grp_fu_1233_p10;
wire   [51:0] tmp5_fu_1187_p00;
wire   [51:0] tmp5_fu_1187_p10;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 56'd1;
#0 threshold_V = 8'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

hls_otsu_front_pibkb #(
    .DataWidth( 20 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
front_pixs_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(front_pixs_V_address0),
    .ce0(front_pixs_V_ce0),
    .we0(front_pixs_V_we0),
    .d0(front_pixs_V_d0),
    .q0(front_pixs_V_q0)
);

hls_otsu_front_grcud #(
    .DataWidth( 28 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
front_grays_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(front_grays_V_address0),
    .ce0(front_grays_V_ce0),
    .we0(front_grays_V_we0),
    .d0(front_grays_V_d0),
    .q0(front_grays_V_q0)
);

hls_otsu_hist_out_V #(
    .DataWidth( 19 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hist_out_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hist_out_V_address0),
    .ce0(hist_out_V_ce0),
    .we0(hist_out_V_we0),
    .d0(19'd0),
    .q0(hist_out_V_q0),
    .address1(hist_out_V_address1),
    .ce1(hist_out_V_ce1),
    .we1(hist_out_V_we1),
    .d1(hist_out_V_d1)
);

hls_ocr_udiv_34nsdEe #(
    .ID( 1 ),
    .NUM_STAGE( 38 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 34 ))
hls_ocr_udiv_34nsdEe_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1118_ap_start),
    .done(grp_fu_1118_ap_done),
    .din0(grp_fu_1118_p0),
    .din1(grp_fu_1118_p1),
    .ce(1'b1),
    .dout(grp_fu_1118_p2)
);

hls_ocr_udiv_26nseOg #(
    .ID( 1 ),
    .NUM_STAGE( 30 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 26 ))
hls_ocr_udiv_26nseOg_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1132_ap_start),
    .done(grp_fu_1132_ap_done),
    .din0(grp_fu_1132_p0),
    .din1(grp_fu_1132_p1),
    .ce(1'b1),
    .dout(grp_fu_1132_p2)
);

hls_ocr_udiv_34nsdEe #(
    .ID( 1 ),
    .NUM_STAGE( 38 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 34 ))
hls_ocr_udiv_34nsdEe_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1148_ap_start),
    .done(grp_fu_1148_ap_done),
    .din0(grp_fu_1148_p0),
    .din1(grp_fu_1148_p1),
    .ce(1'b1),
    .dout(grp_fu_1148_p2)
);

hls_ocr_mul_52s_5fYi #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 52 ),
    .din1_WIDTH( 52 ),
    .dout_WIDTH( 52 ))
hls_ocr_mul_52s_5fYi_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp9_reg_1587),
    .din1(tmp5_reg_1592),
    .ce(1'b1),
    .dout(grp_fu_1193_p2)
);

hls_ocr_mul_mul_1g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 20 ))
hls_ocr_mul_mul_1g8j_U19(
    .din0(total_pixs_V_fu_1229_p0),
    .din1(total_pixs_V_fu_1229_p1),
    .dout(total_pixs_V_fu_1229_p2)
);

hls_ocr_mac_muladhbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
hls_ocr_mac_muladhbi_U20(
    .din0(grp_fu_1233_p0),
    .din1(grp_fu_1233_p1),
    .din2(front_grays_tmp_V_1_fu_246),
    .dout(grp_fu_1233_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_1061_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_i_fu_550_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_5_i_fu_535_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter2_state6)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_5_i_fu_535_p2 == 1'd1)))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter2_state6))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_5_i_fu_535_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1))) begin
        addr_last_V_fu_226 <= addr_win_val_0_V_3_fu_222;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        addr_last_V_fu_226 <= 8'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1))) begin
        addr_win_val_0_V_1_2_fu_218 <= addr_win_val_V_0_0_2_fu_781_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        addr_win_val_0_V_1_2_fu_218 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1))) begin
        addr_win_val_0_V_2_fu_214 <= addr_win_val_0_V_1_2_fu_218;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        addr_win_val_0_V_2_fu_214 <= 8'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1))) begin
        addr_win_val_0_V_3_fu_222 <= addr_win_val_0_V_2_fu_214;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        addr_win_val_0_V_3_fu_222 <= 8'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_5_i_fu_535_p2 == 1'd0))) begin
        col_assign_reg_421 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (exitcond4_i_fu_946_p2 == 1'd0))) begin
        col_assign_reg_421 <= m_fu_952_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) & (tmp_32_i_fu_1210_p2 == 1'd1))) begin
        delta_max_V_fu_254 <= delta_temp_V_reg_1597;
    end else if (((1'b1 == ap_CS_fsm_state11) & (exitcond5_i_fu_986_p2 == 1'd1))) begin
        delta_max_V_fu_254 <= 34'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_15_i_reg_1491 == 1'd0))) begin
        front_grays_tmp_V_1_fu_246 <= grp_fu_1233_p3;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd1))) begin
        front_grays_tmp_V_1_fu_246 <= 28'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        if ((tmp_15_i_fu_1008_p2 == 1'd1)) begin
            front_pixs_tmp_V_1_fu_250 <= 20'd0;
        end else if ((tmp_15_i_fu_1008_p2 == 1'd0)) begin
            front_pixs_tmp_V_1_fu_250 <= front_pixs_tmp_V_fu_1022_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter2_reg == 1'd1))) begin
        hist_win_val_0_V_1_4_fu_234 <= hist_win_val_V_0_0_2_fu_910_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        hist_win_val_0_V_1_4_fu_234 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter2_reg == 1'd1))) begin
        hist_win_val_0_V_2_fu_230 <= hist_win_val_0_V_1_2_fu_876_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        hist_win_val_0_V_2_fu_230 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter2_reg == 1'd1))) begin
        hist_win_val_0_V_3_4_fu_242 <= hist_win_val_0_V_3_2_fu_835_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        hist_win_val_0_V_3_4_fu_242 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter2_reg == 1'd1))) begin
        hist_win_val_0_V_3_fu_238 <= hist_win_val_0_V_2_2_fu_855_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        hist_win_val_0_V_3_fu_238 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (srcImg_cols_V_empty_n == 1'b0) | (srcImg_rows_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i3_i_reg_388 <= 9'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd0))) begin
        i3_i_reg_388 <= i_fu_474_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i4_i_reg_399 <= i_1_reg_1345;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        i4_i_reg_399 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i_op_assign_reg_432 <= i_2_reg_1458;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        i_op_assign_reg_432 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_i_fu_550_p2 == 1'd1))) begin
        j_i_reg_410 <= j_fu_555_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_5_i_fu_535_p2 == 1'd1))) begin
        j_i_reg_410 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        val_assign_reg_444 <= i_3_reg_1508;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        val_assign_reg_444 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1))) begin
        addr_win_val_0_V_1_fu_210 <= addr_win_val_0_V_1_1_fu_714_p3;
        addr_win_val_0_V_2_2_reg_1373 <= addr_win_val_0_V_2_fu_214;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        black_grays_V_reg_1528 <= black_grays_V_fu_1084_p2;
        f_op_V_1_reg_1536 <= f_op_V_1_fu_1100_p3;
        p_Val2_3_reg_1523 <= front_grays_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        delta_temp_V_reg_1597 <= {{grp_fu_1193_p2[51:18]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
        extLd12_cast_i_reg_1331 <= extLd12_cast_i_fu_485_p1;
        extLd_cast_i_reg_1336 <= extLd_cast_i_fu_488_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        front_grays_V_load_reg_1495 <= front_grays_V_q0;
        tmp_1_i_reg_1500[19 : 0] <= tmp_1_i_fu_1058_p1[19 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_1061_p2 == 1'd0))) begin
        front_pixs_V_addr_2_reg_1513 <= tmp_20_i_fu_1073_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        hist_out_V_load_reg_1486 <= hist_out_V_q0;
        tmp_15_i_reg_1491 <= tmp_15_i_fu_1008_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter2_reg == 1'd1))) begin
        hist_win_val_0_V_1_fu_206 <= hist_win_val_0_V_1_3_fu_883_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_1_reg_1345 <= i_1_fu_540_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_2_reg_1458 <= i_2_fu_992_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_3_reg_1508 <= i_3_fu_1067_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1))) begin
        icmp_reg_1406 <= icmp_fu_748_p2;
        sel_tmp5_reg_1411 <= sel_tmp5_fu_768_p2;
        tmp_34_i_reg_1396 <= tmp_34_i_fu_722_p2;
        tmp_49_1_i_reg_1384 <= tmp_49_1_i_fu_694_p2;
        tmp_51_2_i_reg_1390 <= tmp_51_2_i_fu_708_p2;
        tmp_51_i_reg_1378 <= tmp_51_i_fu_680_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        r_V_5_reg_1566 <= grp_fu_1132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        r_V_6_reg_1572 <= grp_fu_1118_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        r_V_reg_1582 <= r_V_fu_1166_p2;
        w1_V_reg_1577 <= w1_V_fu_1154_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (srcImg_cols_V_empty_n == 1'b0) | (srcImg_rows_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcImg_cols_V_read_reg_1249 <= srcImg_cols_V_dout;
        srcImg_rows_V_read_reg_1243 <= srcImg_rows_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) & (tmp_32_i_fu_1210_p2 == 1'd1))) begin
        threshold_V <= tmp_2_fu_1215_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        tmp5_reg_1592 <= tmp5_fu_1187_p2;
        tmp9_reg_1587 <= tmp9_fu_1181_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (exitcond5_i_fu_986_p2 == 1'd0))) begin
        tmp_2_i_reg_1463[8 : 0] <= tmp_2_i_fu_998_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_i_reg_1350 == 1'd1))) begin
        tmp_3_reg_1359 <= srcImg_data_stream_V_dout;
        tmp_7_i_reg_1369 <= tmp_7_i_fu_565_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_6_i_reg_1350 <= tmp_6_i_fu_550_p2;
        tmp_6_i_reg_1350_pp0_iter1_reg <= tmp_6_i_reg_1350;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_6_i_reg_1350_pp0_iter2_reg <= tmp_6_i_reg_1350_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        total_pixs_V_reg_1438 <= total_pixs_V_fu_1229_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_1061_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_7_i_reg_1369 == 1'd0) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_7_i_reg_1369 == 1'd1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        dstImg_data_stream_V_blk_n = dstImg_data_stream_V_full_n;
    end else begin
        dstImg_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op133_write_state6 == 1'b1)) begin
            dstImg_data_stream_V_din = 8'd0;
        end else if ((ap_predicate_op130_write_state6 == 1'b1)) begin
            dstImg_data_stream_V_din = 8'd255;
        end else begin
            dstImg_data_stream_V_din = 'bx;
        end
    end else begin
        dstImg_data_stream_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op133_write_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_predicate_op130_write_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        dstImg_data_stream_V_write = 1'b1;
    end else begin
        dstImg_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        front_grays_V_address0 = tmp_20_i_fu_1073_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        front_grays_V_address0 = tmp_2_i_reg_1463;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        front_grays_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        front_grays_V_address0 = 64'd255;
    end else begin
        front_grays_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        front_grays_V_ce0 = 1'b1;
    end else begin
        front_grays_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        front_grays_V_d0 = grp_fu_1233_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        front_grays_V_d0 = 28'd0;
    end else begin
        front_grays_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & (tmp_15_i_reg_1491 == 1'd0)) | ((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd1)))) begin
        front_grays_V_we0 = 1'b1;
    end else begin
        front_grays_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        front_pixs_V_address0 = front_pixs_V_addr_2_reg_1513;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        front_pixs_V_address0 = tmp_20_i_fu_1073_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd1))) begin
        front_pixs_V_address0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd0))) begin
        front_pixs_V_address0 = tmp_2_i_reg_1463;
    end else begin
        front_pixs_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | ((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd0)))) begin
        front_pixs_V_ce0 = 1'b1;
    end else begin
        front_pixs_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        front_pixs_V_d0 = 20'd1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd1))) begin
        front_pixs_V_d0 = tmp_16_i_fu_1014_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd0))) begin
        front_pixs_V_d0 = front_pixs_tmp_V_fu_1022_p2;
    end else begin
        front_pixs_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state16) & (tmp_21_i_fu_1089_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state12) & (tmp_15_i_fu_1008_p2 == 1'd0)))) begin
        front_pixs_V_we0 = 1'b1;
    end else begin
        front_pixs_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_1118_ap_start = 1'b1;
    end else begin
        grp_fu_1118_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1132_ap_start = 1'b1;
    end else begin
        grp_fu_1132_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1148_ap_start = 1'b1;
    end else begin
        grp_fu_1148_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hist_out_V_address0 = tmp_2_i_fu_998_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        hist_out_V_address0 = tmp_35_i_fu_728_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_out_V_address0 = tmp_3_i_fu_480_p1;
    end else begin
        hist_out_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hist_out_V_address1 = tmp_i_19_fu_972_p1;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        hist_out_V_address1 = tmp_39_i_fu_917_p1;
    end else begin
        hist_out_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        hist_out_V_ce0 = 1'b1;
    end else begin
        hist_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        hist_out_V_ce1 = 1'b1;
    end else begin
        hist_out_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hist_out_V_d1 = hist_win_val_V_load_s_fu_977_p3;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        hist_out_V_d1 = hist_win_val_0_V_2_2_fu_855_p3;
    end else begin
        hist_out_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd0))) begin
        hist_out_V_we0 = 1'b1;
    end else begin
        hist_out_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (exitcond4_i_fu_946_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_6_i_reg_1350_pp0_iter2_reg == 1'd1)))) begin
        hist_out_V_we1 = 1'b1;
    end else begin
        hist_out_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_1061_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcImg_cols_V_blk_n = srcImg_cols_V_empty_n;
    end else begin
        srcImg_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (srcImg_cols_V_empty_n == 1'b0) | (srcImg_rows_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcImg_cols_V_read = 1'b1;
    end else begin
        srcImg_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_i_reg_1350 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        srcImg_data_stream_V_blk_n = srcImg_data_stream_V_empty_n;
    end else begin
        srcImg_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_i_reg_1350 == 1'd1))) begin
        srcImg_data_stream_V_read = 1'b1;
    end else begin
        srcImg_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcImg_rows_V_blk_n = srcImg_rows_V_empty_n;
    end else begin
        srcImg_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (srcImg_cols_V_empty_n == 1'b0) | (srcImg_rows_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcImg_rows_V_read = 1'b1;
    end else begin
        srcImg_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (srcImg_cols_V_empty_n == 1'b0) | (srcImg_rows_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_i_fu_468_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (tmp_5_i_fu_535_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (exitcond4_i_fu_946_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (exitcond5_i_fu_986_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_1061_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign addr_win_val_0_V_1_1_fu_714_p3 = ((tmp_51_2_i_fu_708_p2[0:0] === 1'b1) ? addr_win_val_0_V_1_2_fu_218 : addr_win_val_0_V_2_1_fu_700_p3);

assign addr_win_val_0_V_2_1_fu_700_p3 = ((tmp_49_1_i_fu_694_p2[0:0] === 1'b1) ? addr_win_val_0_V_2_fu_214 : addr_win_val_0_V_3_1_fu_686_p3);

assign addr_win_val_0_V_3_1_fu_686_p3 = ((tmp_51_i_fu_680_p2[0:0] === 1'b1) ? addr_win_val_0_V_3_fu_222 : addr_win_val_0_V_1_fu_210);

assign addr_win_val_V_0_0_2_fu_781_p3 = ((sel_tmp5_fu_768_p2[0:0] === 1'b1) ? addr_last_V_fu_226 : sel_tmp8_fu_774_p3);

assign addr_win_val_V_load_s_fu_964_p3 = ((cond_i_fu_958_p2[0:0] === 1'b1) ? addr_win_val_0_V_1_2_fu_218 : addr_win_val_0_V_2_fu_214);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((ap_predicate_op133_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)) | ((ap_predicate_op130_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)))) | ((srcImg_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_6_i_reg_1350 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((ap_predicate_op133_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)) | ((ap_predicate_op130_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)))) | ((srcImg_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_6_i_reg_1350 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((ap_predicate_op133_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)) | ((ap_predicate_op130_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)))) | ((srcImg_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_6_i_reg_1350 == 1'd1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (srcImg_cols_V_empty_n == 1'b0) | (srcImg_rows_V_empty_n == 1'b0) | (real_start == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((srcImg_data_stream_V_empty_n == 1'b0) & (tmp_6_i_reg_1350 == 1'd1));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((ap_predicate_op133_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)) | ((ap_predicate_op130_write_state6 == 1'b1) & (dstImg_data_stream_V_full_n == 1'b0)));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op130_write_state6 = ((tmp_7_i_reg_1369 == 1'd0) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op133_write_state6 = ((tmp_7_i_reg_1369 == 1'd1) & (tmp_6_i_reg_1350_pp0_iter1_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign black_grays_V_fu_1084_p2 = (front_grays_V_load_reg_1495 - front_grays_V_q0);

assign black_pixs_V_fu_1079_p2 = ($signed(total_pixs_V_reg_1438) - $signed(front_pixs_V_q0));

assign cond_i_fu_958_p2 = ((col_assign_reg_421 == 2'd0) ? 1'b1 : 1'b0);

assign exitcond3_i_fu_468_p2 = ((i3_i_reg_388 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond4_i_fu_946_p2 = ((col_assign_reg_421 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond5_i_fu_986_p2 = ((i_op_assign_reg_432 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_i_fu_1061_p2 = ((val_assign_reg_444 == 9'd256) ? 1'b1 : 1'b0);

assign extLd12_cast_i_fu_485_p1 = srcImg_cols_V_read_reg_1249;

assign extLd_cast_i_fu_488_p1 = srcImg_rows_V_read_reg_1243;

assign f_op_V_1_fu_1100_p3 = ((tmp_22_i_fu_1095_p2[0:0] === 1'b1) ? 20'd1 : black_pixs_V_fu_1079_p2);

assign front_pixs_tmp_V_fu_1022_p2 = (front_pixs_tmp_V_1_fu_250 + tmp_16_i_fu_1014_p1);

assign grp_fu_1118_p0 = {{black_grays_V_reg_1528}, {6'd0}};

assign grp_fu_1118_p1 = grp_fu_1118_p10;

assign grp_fu_1118_p10 = f_op_V_1_reg_1536;

assign grp_fu_1132_p0 = {{front_pixs_V_q0}, {6'd0}};

assign grp_fu_1132_p1 = tmp_1_i_reg_1500;

assign grp_fu_1148_p0 = {{p_Val2_3_reg_1523}, {6'd0}};

assign grp_fu_1148_p1 = grp_fu_1148_p10;

assign grp_fu_1148_p10 = front_pixs_V_q0;

assign grp_fu_1233_p0 = grp_fu_1233_p00;

assign grp_fu_1233_p00 = hist_out_V_load_reg_1486;

assign grp_fu_1233_p1 = grp_fu_1233_p10;

assign grp_fu_1233_p10 = i_op_assign_reg_432;

assign hist_last_V_fu_823_p2 = (hist_win_val_0_V_3_4_fu_242 + 19'd1);

assign hist_win_val_0_V_0_fu_890_p2 = (hist_out_V_q0 + 19'd1);

assign hist_win_val_0_V_1_1_fu_870_p2 = (hist_win_val_0_V_1_4_fu_234 + 19'd1);

assign hist_win_val_0_V_1_2_fu_876_p3 = ((tmp_51_2_i_reg_1390[0:0] === 1'b1) ? hist_win_val_0_V_1_1_fu_870_p2 : hist_win_val_0_V_1_4_fu_234);

assign hist_win_val_0_V_1_3_fu_883_p3 = ((tmp_51_2_i_reg_1390[0:0] === 1'b1) ? hist_win_val_0_V_1_1_fu_870_p2 : hist_win_val_0_V_2_3_fu_863_p3);

assign hist_win_val_0_V_2_1_fu_849_p2 = (hist_win_val_0_V_2_fu_230 + 19'd1);

assign hist_win_val_0_V_2_2_fu_855_p3 = ((tmp_49_1_i_reg_1384[0:0] === 1'b1) ? hist_win_val_0_V_2_1_fu_849_p2 : hist_win_val_0_V_2_fu_230);

assign hist_win_val_0_V_2_3_fu_863_p3 = ((tmp_49_1_i_reg_1384[0:0] === 1'b1) ? hist_win_val_0_V_2_1_fu_849_p2 : hist_win_val_0_V_3_3_fu_842_p3);

assign hist_win_val_0_V_3_1_fu_829_p2 = (hist_win_val_0_V_3_fu_238 + 19'd1);

assign hist_win_val_0_V_3_2_fu_835_p3 = ((tmp_51_i_reg_1378[0:0] === 1'b1) ? hist_win_val_0_V_3_1_fu_829_p2 : hist_win_val_0_V_3_fu_238);

assign hist_win_val_0_V_3_3_fu_842_p3 = ((tmp_51_i_reg_1378[0:0] === 1'b1) ? hist_win_val_0_V_3_1_fu_829_p2 : hist_win_val_0_V_1_fu_206);

assign hist_win_val_V_0_0_2_fu_910_p3 = ((sel_tmp5_reg_1411[0:0] === 1'b1) ? hist_last_V_fu_823_p2 : sel_tmp9_fu_903_p3);

assign hist_win_val_V_load_s_fu_977_p3 = ((cond_i_fu_958_p2[0:0] === 1'b1) ? hist_win_val_0_V_1_4_fu_234 : hist_win_val_0_V_2_fu_230);

assign i4_cast_cast_i_fu_531_p1 = i4_i_reg_399;

assign i_1_fu_540_p2 = (i4_i_reg_399 + 9'd1);

assign i_2_fu_992_p2 = (i_op_assign_reg_432 + 9'd1);

assign i_3_fu_1067_p2 = (val_assign_reg_444 + 9'd1);

assign i_fu_474_p2 = (i3_i_reg_388 + 9'd1);

assign icmp_fu_748_p2 = ((tmp_fu_738_p4 != 2'd0) ? 1'b1 : 1'b0);

assign j_cast_cast_i_fu_546_p1 = j_i_reg_410;

assign j_fu_555_p2 = (j_i_reg_410 + 10'd1);

assign m_fu_952_p2 = (col_assign_reg_421 + 2'd1);

assign p_6_i_fu_666_p3 = ((tmp_8_fu_660_p2[0:0] === 1'b1) ? sel_tmp3_cast_fu_652_p3 : sel_tmp_fu_614_p3);

assign p_i_cast_fu_600_p3 = ((tmp_28_i_fu_580_p2[0:0] === 1'b1) ? 3'd0 : 3'd3);

assign r_V_1_fu_674_p2 = (p_6_i_fu_666_p3 + 3'd1);

assign r_V_fu_1166_p2 = (tmp_29_i_fu_1159_p1 - tmp_30_i_fu_1163_p1);

assign sel_tmp1_fu_622_p2 = (tmp_28_i_fu_580_p2 ^ 1'd1);

assign sel_tmp2_fu_628_p2 = (tmp_28_1_i_fu_585_p2 & sel_tmp1_fu_622_p2);

assign sel_tmp3_cast_fu_652_p3 = ((sel_tmp7_fu_646_p2[0:0] === 1'b1) ? 3'd2 : 3'd1);

assign sel_tmp4_fu_762_p2 = (tmp_34_i_fu_722_p2 ^ 1'd1);

assign sel_tmp5_fu_768_p2 = (tmp_37_i_fu_732_p2 & sel_tmp4_fu_762_p2);

assign sel_tmp6_demorgan_fu_634_p2 = (tmp_28_i_fu_580_p2 | tmp_28_1_i_fu_585_p2);

assign sel_tmp6_fu_640_p2 = (sel_tmp6_demorgan_fu_634_p2 ^ 1'd1);

assign sel_tmp7_fu_646_p2 = (tmp_28_2_i_fu_590_p2 & sel_tmp6_fu_640_p2);

assign sel_tmp8_fu_774_p3 = ((tmp_34_i_fu_722_p2[0:0] === 1'b1) ? tmp_3_reg_1359 : storemerge1_i_fu_754_p3);

assign sel_tmp9_fu_903_p3 = ((tmp_34_i_reg_1396[0:0] === 1'b1) ? hist_win_val_0_V_0_fu_890_p2 : storemerge_i_fu_896_p3);

assign sel_tmp_fu_614_p3 = ((tmp_7_fu_608_p2[0:0] === 1'b1) ? p_i_cast_fu_600_p3 : 3'd4);

assign start_out = real_start;

assign storemerge1_i_fu_754_p3 = ((icmp_fu_748_p2[0:0] === 1'b1) ? addr_win_val_0_V_1_1_fu_714_p3 : addr_win_val_0_V_2_fu_214);

assign storemerge_i_fu_896_p3 = ((icmp_reg_1406[0:0] === 1'b1) ? hist_win_val_0_V_1_3_fu_883_p3 : hist_win_val_0_V_2_2_fu_855_p3);

assign tmp5_fu_1187_p0 = tmp5_fu_1187_p00;

assign tmp5_fu_1187_p00 = w1_V_reg_1577;

assign tmp5_fu_1187_p1 = tmp5_fu_1187_p10;

assign tmp5_fu_1187_p10 = r_V_5_reg_1566;

assign tmp5_fu_1187_p2 = (tmp5_fu_1187_p0 * tmp5_fu_1187_p1);

assign tmp9_fu_1181_p0 = tmp_6_fu_1178_p1;

assign tmp9_fu_1181_p1 = tmp_6_fu_1178_p1;

assign tmp9_fu_1181_p2 = ($signed(tmp9_fu_1181_p0) * $signed(tmp9_fu_1181_p1));

assign tmp_15_i_fu_1008_p2 = ((i_op_assign_reg_432 == 9'd0) ? 1'b1 : 1'b0);

assign tmp_16_i_fu_1014_p1 = hist_out_V_q0;

assign tmp_1_i_fu_1058_p1 = $unsigned(total_pixs_V_reg_1438);

assign tmp_20_i_fu_1073_p1 = val_assign_reg_444;

assign tmp_21_i_fu_1089_p2 = ((front_pixs_V_q0 == 20'd0) ? 1'b1 : 1'b0);

assign tmp_22_i_fu_1095_p2 = ((total_pixs_V_reg_1438 == front_pixs_V_q0) ? 1'b1 : 1'b0);

assign tmp_28_1_i_fu_585_p2 = ((tmp_3_reg_1359 == addr_win_val_0_V_2_fu_214) ? 1'b1 : 1'b0);

assign tmp_28_2_i_fu_590_p2 = ((tmp_3_reg_1359 == addr_win_val_0_V_3_fu_222) ? 1'b1 : 1'b0);

assign tmp_28_3_i_fu_595_p2 = ((tmp_3_reg_1359 == addr_last_V_fu_226) ? 1'b1 : 1'b0);

assign tmp_28_i_fu_580_p2 = ((tmp_3_reg_1359 == addr_win_val_0_V_1_2_fu_218) ? 1'b1 : 1'b0);

assign tmp_29_i_fu_1159_p1 = grp_fu_1148_p2;

assign tmp_2_fu_1215_p1 = val_assign_reg_444[7:0];

assign tmp_2_i_fu_998_p1 = i_op_assign_reg_432;

assign tmp_30_i_fu_1163_p1 = r_V_6_reg_1572;

assign tmp_32_i_fu_1210_p2 = ((delta_temp_V_reg_1597 > delta_max_V_fu_254) ? 1'b1 : 1'b0);

assign tmp_34_i_fu_722_p2 = ((p_6_i_fu_666_p3 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_35_i_fu_728_p1 = tmp_3_reg_1359;

assign tmp_37_i_fu_732_p2 = ((p_6_i_fu_666_p3 == 3'd3) ? 1'b1 : 1'b0);

assign tmp_39_i_fu_917_p1 = addr_win_val_0_V_2_2_reg_1373;

assign tmp_3_i_fu_480_p1 = i3_i_reg_388;

assign tmp_49_1_i_fu_694_p2 = ((r_V_1_fu_674_p2 == 3'd2) ? 1'b1 : 1'b0);

assign tmp_51_2_i_fu_708_p2 = ((p_6_i_fu_666_p3 == 3'd0) ? 1'b1 : 1'b0);

assign tmp_51_i_fu_680_p2 = ((r_V_1_fu_674_p2 == 3'd3) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_535_p2 = (($signed(i4_cast_cast_i_fu_531_p1) < $signed(srcImg_rows_V_read_reg_1243)) ? 1'b1 : 1'b0);

assign tmp_6_fu_1178_p1 = $signed(r_V_reg_1582);

assign tmp_6_i_fu_550_p2 = (($signed(j_cast_cast_i_fu_546_p1) < $signed(srcImg_cols_V_read_reg_1249)) ? 1'b1 : 1'b0);

assign tmp_7_fu_608_p2 = (tmp_28_i_fu_580_p2 | tmp_28_3_i_fu_595_p2);

assign tmp_7_i_fu_565_p2 = ((srcImg_data_stream_V_dout > threshold_V) ? 1'b1 : 1'b0);

assign tmp_8_fu_660_p2 = (sel_tmp7_fu_646_p2 | sel_tmp2_fu_628_p2);

assign tmp_fu_738_p4 = {{p_6_i_fu_666_p3[2:1]}};

assign tmp_i_19_fu_972_p1 = addr_win_val_V_load_s_fu_964_p3;

assign total_pixs_V_fu_1229_p0 = extLd12_cast_i_reg_1331;

assign total_pixs_V_fu_1229_p1 = extLd_cast_i_reg_1336;

assign w1_V_fu_1154_p2 = (26'd64 - r_V_5_reg_1566);

always @ (posedge ap_clk) begin
    tmp_2_i_reg_1463[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_1_i_reg_1500[25:20] <= 6'b000000;
end

endmodule //hls_otsu
